### ISSUE TITLE
3.0 feedback

### ISSUE THREAD

**Issue by popomore** [eggjs/eslint-config-egg#14]
待讨论规则

- [x] dot-notation
- [x] no-magic-numbers
- [ ] no-console
- [ ] valid-jsdoc
- [x] quote-props
- [x] prefer-template
- [ ] no-extra-parens
- [x] max-len
- [x] no-unused-expressions

**Comment by popomore** [comment]
`Symbol.for('egg#loader')`

.for is a syntax error                          dot-notation

**Comment by fengmk2** [comment]
- no-magic-numbers 要设置为 off
- no-console 很难避免的

```js
let pkg;
try {
  pkg = require(path.join(root, 'package.json'));
} catch (err) {
  console.error('read package.json error: %s', err.message);
  console.error('[egg-ci] stop create ci yml');
  process.exit(0);
}
```

**Comment by popomore** [comment]
Line 37 exceeds the maximum line length of 100   max-len

有点短

**Comment by atian25** [comment]
`valid-jsdoc` 这个,  `@returns` 和 ``@return` 是否允许同时存在?

用 webstorm 的时候, 默认生成的是 `@returns`, 但手写一般都是 `@return`

**Comment by popomore** [comment]
Unquoted reserved word 'package' used as key  quote-props

**Comment by atian25** [comment]
```
// config/plugin.js
exports.combo = {
  package: '@ali/egg-combo'
};
```

`Unquoted reserved word 'package' used as key  quote-props`

**Comment by atian25** [comment]
`4:25  error  Gratuitous parentheses around expression  no-extra-parens`

会导致下面这种写法提示错误
```
module.exports = app => (
   class Test extends app.Proxy {
   }
);
```

因为下面这种写法也会提示错误, 我会倾向于上面那种写法.
```
module.exports = app => {
   return class Test extends app.Proxy {
   }
};
```

**Comment by atian25** [comment]
@fengmk2 在 egg 里面, 应该很少用 console 吧?  logger 呢?

**Comment by popomore** [comment]
quote-props 感觉也可以用掉

**Comment by popomore** [comment]
用下来感觉 prefer-template 也太强制了

**Comment by popomore** [comment]
已经整理到上面了

**Comment by atian25** [comment]
嗯，template 那个不够智能，很短的也要求用。

**Comment by atian25** [comment]
配套的 eslint 用3.x ？

**Comment by fengmk2** [comment]
generator-star-spaceing 有问题，有没空格都是 ok 的，可不写就不写。

**Comment by fengmk2** [comment]
prefer-template 设置为 off 吧

**Comment by fengmk2** [comment]
像正则很可能就超过 max-len 了。。。

```
        .should.match(/\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3} INFO \d+ \[-\/-\/127.0.0.1\/-\/0ms GET \/\] info foo\n/);

```

**Comment by atian25** [comment]
@fengmk2 我之前的实践是:

- 提供一个 egg/test 的规则集, 在测试脚本里面适当的放松规则.
- 正式代码里面遇到 max-len 这种少数场景, 单独使用 `// eslint-disable-line max-len`

**Comment by popomore** [comment]
设 132 吧，或者不要设置了，对我们编码其实影响不大

http://programmers.stackexchange.com/questions/148677/why-is-80-characters-the-standard-limit-for-code-width

**Comment by popomore** [comment]
dot-notation allowKeywords 设为 true

no-magic-numbers 关掉

quote-props 关闭 keywork

**Comment by popomore** [comment]
no-unused-expressions 会导致 `app1.use.should.be.a.Function;` 挂掉

**Comment by atian25** [comment]
prefer-template，no-extra-parens 也关掉吧。。

 no-console 我感觉是使用场景少，可以开着？

 valid-jsdoc 这个只是想看看有没有同时兼容两种 return 的配置。关的话会不会使其他文档注释不规范？ 感觉可以开着。

**Comment by popomore** [comment]
这个大家再看看，我一起改了

**Comment by atian25** [comment]
再提供一个 egg/lib/test 的规则集，适当放松一些规则，如 func-name之类的

**Comment by popomore** [comment]
感觉没必要吧，都是 js 为啥要区分

**Comment by atian25** [comment]
也行吧，我之前的实践是，测试里面的函数无需有名字，还有关闭maxlen之类的。

**Comment by popomore** [comment]
写成 arrow function 呗

**Comment by atian25** [comment]
generater function 也受那个规则限制。不过可以无视这个需求了。

**Comment by atian25** [comment]
3.0.3 建议:

- [ ] [`valid-jsdoc: [ 'error', { prefer: { returns: 'return' }, requireReturn: false}]`](http://eslint.org/docs/rules/valid-jsdoc)
 - 这条上面提过, 是否允许 return 和 returns 同时存在?
 - 如果允许, 干掉 `returns: 'return'` 即可
- [ ] [`brace-style: [ 'error', '1tbs', { allowSingleLine: true } ]`](http://eslint.org/docs/rules/brace-style)
- [ ] [`no-extra-parens: [ 'error', 'functions' ]`](http://eslint.org/docs/rules/no-extra-parens)
```
module.export = app => (
  /**
   * 不用 return, 还能写注释
   */
  class Test extends app.Proxy {
  
 }
);
```

**Comment by dead-horse** [comment]
https://github.com/eslint/espree/issues/140 使用的这个 parser 不支持 async function，我好想不能在外部的 eslintrc 上覆盖掉这个 parser... 换成 babel-eslint 会报错

**Comment by dead-horse** [comment]
切换成 babel-eslint 后因为这个报错： https://github.com/eslint/eslint/issues/6274

可以设置 rules 为：

```
"generator-star-spacing": 0,
"babel/generator-star-spacing": 0,
```

我们的 parser 用 babel-eslint ? ava 写测试的时候引入了 async function

**Comment by dead-horse** [comment]
```
sourceType: 'modules',
```

这一句写错了，正确的应该是 `module`，但是如果设置成 `module` 其实是要用 import 和 export，且不写 'use strcit'， 所以应该是写成 `sourceType: 'script'` ?

**Comment by dead-horse** [comment]
console 还是会用到，如果要开着的话我要用 `const logger = console` 来避免，感觉有点蛋疼

**Comment by atian25** [comment]
sourceType 不应该是 module

**Comment by atian25** [comment]
console 关+1 。 我现在是前端代码那里单独配置，不允许 log ，可以 error 和 warn

**Comment by popomore** [comment]
我建议 eslint-config-egg 不要加 node 不支持的特性，这个本身是用于 node 的代码规范，如果要公用那就覆盖他好了。

**Comment by popomore** [comment]
我看文档  script 是默认的

**Comment by atian25** [comment]
react相关的是不是独立一个库？ 印象中应用那里可以 extend多个的。

**Comment by atian25** [comment]
或者还在这个里面，但只是 export 出来，不默认使用。

**Comment by popomore** [comment]
是遍历每一层目录然后合并的，在前端目录放个配置就好了，而且前端框架也比较多，很多人会直接用 airbnb 之类的。

**Comment by atian25** [comment]
我的意思是:

egg 可以 export 多个, 如 egg 和 egg/lib/react, 然后 views 里面继承多个.

```yaml
// .eslintrc.yml
---
extends: egg
rules:
  no-console: 'off'

// app/views/.eslintrc.yml
---
extends: 
  - ../../.eslintrc.yml
  - egg/lib/react

parserOptions:
  sourceType: "module"
  ecmaFeatures:
    experimentalObjectRestSpread: true

rules:
  no-console: [ "error", { allow: ["info", "warn", "error"] } ]
```

**Comment by atian25** [comment]
@dead-horse 在那个 PR 里面我改了 `sourceType` 和 `no-console`

**Comment by dead-horse** [comment]
前端的不用默认配置，export 一份或者在文档里面说明（感觉文档说明比较合理，否则要引入额外的依赖 eslint-pluin-react 这些）。

不过是否把 parser 默认替换成 babel-eslint 呢？这样默认是支持 es7 语法的，依赖也不大，不过大部分情况下确实也可以让用到 babel 的人自行引入，但是需要文档中注明 `generator-star-spacing` 的坑..

**Comment by dead-horse** [comment]
no-extra-parens 感觉可以关掉，很多时候会加括号来帮助优先级判断，例如：

```js
if (a === 1 || (b === 2 && c === 3) ) {
  // do something
}
```

**Comment by atian25** [comment]
@dead-horse 我在那个 PR 里面改为  `no-extra-parens: [ 'error', 'functions' ]` 了, 只限制函数

http://eslint.org/docs/rules/no-extra-parens

**Comment by popomore** [comment]
@dead-horse 如果是多余的话说明优先级是对的，`&&` 高于 `||`

**Comment by geekdada** [comment]
`no-extra-parens: [ 'error', 'functions' ]` +1

**Comment by dead-horse** [comment]
@popomore 我知道这个优先级是对的，但是对阅读代码来说加一个括号更优

**Comment by atian25** [comment]
@popomore 我个人更喜欢多余的方式, 避免去猜, 就像以前的 ++i++ 之类的

**Comment by fengmk2** [comment]
> @popomore 我个人更喜欢多余的方式, 避免去猜, 就像以前的 ++i++ 之类的

+1

**Comment by popomore** [comment]
好

**Comment by atian25** [comment]
@dead-horse `parser` 那个你新开个 issue ?

**Comment by dead-horse** [comment]
我单独开个 MR，补一下 README 好了，先不将那些引入到 egg 的配置
